# Generated by Django 3.0.9 on 2020-08-06 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='custom_user',
        ),
    ]
